-------------------------
-- Russian Localization String resources
-- MIUI Russia miui.su (2014)
-- VasyaVeselov
-- 20140731
-------------------------
localization_English_table = {
    calories_table={
		{str="≈ Огірок грунт. (100г)", calories=14},
		{str="≈ Бульйон курячий (100г)", calories=15},
		{str="≈ Капуста пекінська (100г)", calories=16},
		{str="≈ Томати солоні (100г)", calories=19},
		{str="≈ Квас (100г)", calories=20},
		{str="≈ Печериці (100г)", calories=20},
		{str="≈ Редис (100г)", calories=21},
		{str="≈ Баклажани (100г)", calories=24},
		{str="≈ Гарбуз (100г)", calories=25},
		{str="≈ Квашена капуста (100г)", calories=25},
		{str="≈ Айран (100г)", calories=26},
		{str="≈ Грибний суп (100г)", calories=26},
		{str="≈ Брокколі (100г)", calories=27},
		{str="≈ Овочевий суп (100г)", calories=28},
		{str="≈ Полуниця (100г)", calories=30},
		{str="≈ Щі (100г)", calories=31},
		{str="≈ Борщ (100г)", calories=36},
		{str="≈ Суп місо (100г)", calories=36},
		{str="≈ Борщ (100г)", calories=36},
		{str="≈ Яблуко (100г)", calories=37},
		{str="≈ Апельсин (100г)", calories=38},
		{str="≈ Картопляний суп (100г)", calories=39},
		{str="≈ Кавун (100г)", calories=39},
		{str="≈ Щавлевий суп (100г)", calories=40},
		{str="≈ Кисле молоко 1% (100г)", calories=40},
		{str="≈ Розсольник (100г)", calories=42},
		{str="≈ Сoca-Cola (100г)", calories=42},
		{str="≈ Молоко 1.5% (100г)", calories=45},
		{str="≈ Red Bull (100г)", calories=45},
		{str="≈ Вуха (100г)", calories=46},
		{str="≈ Персик (100г)", calories=46},
		{str="≈ Сир Hochland (25г)", calories=48},
		{str="≈ Вишня (100г)", calories=52},
		{str="≈ Апельсиновий сік (100г)", calories=54},
		{str="≈ Кефір 3.2% (100г)", calories=56},
		{str="≈ Окрошка (100г)", calories=57},
		{str="≈ Молоко 3.2% (100г)", calories=58},
		{str="≈ Аджика (100г)", calories=59},
		{str="≈ Рататуй (100г)", calories=60},
		{str="≈ Пюре з мол. (100г)", calories=65},
		{str="≈ Гороховий суп (100г)", calories=66},
		{str="≈ Манго (100г)", calories=67},
		{str="≈ Вівсяна каша (100г)", calories=68},
		{str="≈ Суп із сочевиці (100г)", calories=68},
		{str="≈ Полуничне желе (100г)", calories=69},
		{str="≈ Солянка збірна (100г)", calories=69},
		{str="≈ Йогурт 1.5% солод. (100г)", calories=70},
		{str="≈ Крабові палички (100г)", calories=73},
		{str="≈ Суп харчо (100г)", calories=75},
		{str="≈ Кальмари (100г)", calories=75},
		{str="≈ Шампанське (100г)", calories=76},
		{str="≈ Вино 13% (100г)", calories=78},
		{str="≈ Вареники з капустою (100г)", calories=79},
		{str="≈ Гуляш з капустою (100г)", calories=81},
		{str="≈ Картопля відварна (100г)", calories=82},
		{str="≈ Абсент 60% (100г)", calories=83},
		{str="≈ Пюре з мол.і масл. (100г)", calories=85},
		{str="≈ Яйце варене (55г)", calories=88},
		{str="≈ Банан (100г)", calories=89},
		{str="≈ Кабачкова ікра (100г)", calories=90},
		{str="≈ Квасоля в томаті (100г)", calories=92},
		{str="≈ Кетчуп (100г)", calories=93},
		{str="≈ Рис з овочами (100г)", calories=94},
		{str="≈ Зерновий тост (1шт)", calories=95},
		{str="≈ Тунець (100г)", calories=96},
		{str="≈ Судак відварений (100г)", calories=97},
		{str="≈ Манна каша. (100г)", calories=98},
		{str="≈ Овочеве рагу (100г)", calories=99},
		{str="≈ Короп відварений (100г)", calories=102},
		{str="≈ Фруктовий салат (100г)", calories=103},
		{str="≈ Філе індички (100г)", calories=104},
		{str="≈ Свинячий балик (100г)", calories=105},
		{str="≈ Плов з куркою (100г)", calories=106},
		{str="≈ Рис (100г)", calories=113},
		{str="≈ Цепеліни (100г)", calories=117},
		{str="≈ Яєчня", calories=119},
		{str="≈ Ікра кабачкова (100г)", calories=122},
		{str="≈ Японський майонез (100г)", calories=134},
		{str="≈ Зефір (1шт)", calories=135},
		{str="≈ Сир (100г)", calories=136},
		{str="≈ Авокадо рол", calories=140},
		{str="≈ Капучино (100г)", calories=140},
		{str="≈ Лобіо (100г)", calories=141},
		{str="≈ Яловичина, язик (100г)", calories=146},
		{str="≈ Яловичий гуляш (100г)", calories=148},
		{str="≈ Куряче філе вар. (100г)", calories=153},
		{str="≈ Картопля смаж. (100г)", calories=154},
		{str="≈ Піца маргарита (100г)", calories=157},
		{str="≈ Тефтелі (100г)", calories=159},
		{str="≈ Гречана каша (100г)", calories=160},
		{str="≈ Сирок Чудо (40г)", calories=164},
		{str="≈ Хліб житній (100г)", calories=165},
		{str="≈ Смажена індичка (100г)", calories=165},
		{str="≈ Салат мімоза (100г)", calories=183},
		{str="≈ Долма (100г)", calories=183},
		{str="≈ Копчена курка (100г)", calories=184},
		{str="≈ Салат Олів\'є (100г)", calories=187},
		{str="≈ Зрази картопляні (100г)", calories=190},
		{str="≈ Свинячий биток (100г)", calories=195},
		{str="≈ Сардельки (100г)", calories=198},
		{str="≈ Лосось (201г)", calories=201},
		{str="≈ Сметана 20% (100г)", calories=204},
		{str="≈ Вершки (100г)", calories=206},
		{str="≈ Паста болон\'єз (100г)", calories=208},
		{str="≈ Азу (100г)", calories=214},
		{str="≈ Хліб чорний (100г)", calories=214},
		{str="≈ Цукати (100г)", calories=216},
		{str="≈ Салат столичний (100г)", calories=217},
		{str="≈ Оселедець солоний (100г)", calories=217},
		{str="≈ Жульєн грибний (100г)", calories=219},
		{str="≈ Салат цезар (100г)", calories=221},
		{str="≈ Омлет (100г)", calories=222},
		{str="≈ Світле пиво (0,5 л)", calories=225},
		{str="≈ Вівсяний хліб (100г)", calories=226},
		{str="≈ Рагу з баранини (100г)", calories=226},
		{str="≈ Пломбір (100г)", calories=227},
		{str="≈ Гамбургер", calories=229},
		{str="≈ Печеня зі свинини (100г)", calories=233},
		{str="≈ Батон (100г)", calories=235},
		{str="≈ Лаваш (100г)", calories=236},
		{str="≈ Горілка 40% (100г)", calories=237},
		{str="≈ Бастурма (100г)", calories=240},
		{str="≈ Хамон (100г)", calories=241},
		{str="≈ Хліб пшеничний (100г)", calories=242},
		{str="≈ Сосиски молочні (100г)", calories=243},
		{str="≈ Равіолі (100г)", calories=245},
		{str="≈ Червона ікра (100г)", calories=249},
		{str="≈ Шаурма (100г)", calories=250},
		{str="≈ Ковбаса варена (100г)", calories=257},
		{str="≈ Курячі сосиски (100г)", calories=259},
		{str="≈ Котлети (100г)", calories=260},
		{str="≈ Родзинки (100г)", calories=262},
		{str="≈ Чізбургер", calories=264},
		{str="≈ Сосиски дитячі. (100г)", calories=270},
		{str="≈ Шинка (100г)", calories=270},
		{str="≈ Мойва копчена (100г)", calories=270},
		{str="≈ МакНаггетс (100г)", calories=272},
		{str="≈ Кров\'янка (100г)", calories=274},
		{str="≈ М\'ясо в шубі (100г)", calories=274},
		{str="≈ Пельмені (100г)", calories=275},
		{str="≈ Плов зі свининою (100г)", calories=281},
		{str="≈ Лосось гриль (100г)", calories=283},
		{str="≈ Сирок Дружба (100г)", calories=287},
		{str="≈ Чорна ікра (100г)", calories=289},
		{str="≈ Майонез (100г)", calories=299},
		{str="≈ Квітковий мед (100г)", calories=302},
		{str="≈ Картопля фрі (100г)", calories=303},
		{str="≈ Салат Олів\'є (100г)", calories=305},
		{str="≈ Скумбрія солона (100г)", calories=305},
		{str="≈ Фініки (100г)", calories=306},
		{str="≈ Оладки з яблуками (100г)", calories=306},
		{str="≈ Голубці (100г)", calories=311},
		{str="≈ Біляш (100г)", calories=320},
		{str="≈ Оладки (100г)", calories=322},
		{str="≈ Омлет з сиром (100г)", calories=324},
		{str="≈ Ковбаса ліверна (100г)", calories=326},
		{str="≈ Ковбаски мисливські (100г)", calories=326},
		{str="≈ Пончики (100г)", calories=329},
		{str="≈ Ватрушка (100г)", calories=331},
		{str="≈ Млинці з маслом (100г)", calories=332},
		{str="≈ Люля-кебаб (100г)", calories=339},
		{str="≈ Сушки (100г)", calories=341},
		{str="≈ Макарони Макфа (100г)", calories=344},
		{str="≈ Спагетті (100г)", calories=344},
		{str="≈ Кекс (100г)", calories=345},
		{str="≈ Пряник (100г)", calories=350},
		{str="≈ Бефстроганов (100г)", calories=355},
		{str="≈ Російський сир (100г)", calories=360},
		{str="≈ Кукурудзяні пластівці (100г)", calories=363},
		{str="≈ Макарони (100г)", calories=371},
		{str="≈ Біфштекс (100г)", calories=384},
		{str="≈ Сухарі (100г)", calories=386},
		{str="≈ Цукор-пісок (100г)", calories=398},
		{str="≈ Козинаки (100г)", calories=419},
		{str="≈ Вівсяне печиво (100г)", calories=440},
		{str="≈ Локшина Мівіна(100г)", calories=448},
		{str="≈ Торт мурашник (100г)", calories=452},
		{str="≈ Шніцель (100г)", calories=456},
		{str="≈ Лазанья (100г)", calories=460},
		{str="≈ Фуа-гра (100г)", calories=462},
		{str="≈ Торт Медовик (100г)", calories=478},
		{str="≈ Попкорн (100г)", calories=480},
		{str="≈ Твікс", calories=483},
		{str="≈ Снікерс", calories=497},
		{str="≈ Бекон (100г)", calories=500},
		{str="≈ Біг Мак", calories=510},
		{str="≈ Чіпси Lays Max (100г)", calories=510},
		{str="≈ Халва (100г)", calories=522},
		{str="≈ Шоколад KitKat", calories=524},
		{str="≈ Роял Чізбургер (100г)", calories=530},
		{str="≈ Тірамісу (100г)", calories=540},
		{str="≈ Чіпси Pringles (100г)", calories=540},
		{str="≈ Шоколад (100г)", calories=546},
		{str="≈ Торт Наполеон (100г)", calories=552},
		{str="≈ Салямі (100г)", calories=568},
		{str="≈ Гусак смажений (100г)", calories=620},
		{str="≈ Майонез Євр. (100г)", calories=665},
		{str="≈ Пельмені смажені (100г)", calories=764},
		{str="≈ Сало (100г)", calories=797},
    },

    ok='ОК',

    hour='г.',
    minute='хв.',
    month='міс.',
    day='дн.',
    step="к.",
    km=' км',
	mile='миль',
    minute_format='%d хв.',
    hour_minute_format='%d г. %d хв.',
    hour_format='%d г.',

    welcome_use="Ласкаво просимо",
    last_week_walked_format='Кроків за минулий тиждень: %d.',
    last_week_walked_info_format='Пройдено %d км | Спалено %d ккал',
    last_month_walked_format='Кроків за минулий місяць: %d.',
    last_month_walked_info_format='Пройдено %d км | Спалено %d ккал',

    get_over_format=", біля %d г жиру.",
    click_to_get_help="Інформація про Mi Band",
    take_a_walk="Прогуляйтеся з Mi Band",
    take_a_walk_info="Mi Band буде відслідковувати вашу активність протягом дня.",
    unlock_hint="Розблокування за допомогою Mi Band",
    unlock_hint_info="Контролюйте доступ до вашого телефону",
	unlock_password_hint="Настройка блокування екрану для захисту телефону",
    unlock_password_hint_info="Mi Band надає кращий захист екрану",
    no_data_hint_0="Рухайтеся, зробіть спорт частиною свого життя.",
    no_data_hint_1="Хочете бути щасливим? Просто біжіть.",
    no_data_hint_2="Кардіо тренування зроблять тебе бадьорим і енергійним на весь день! ",
    no_data_hint_3="Доросла людина проводить у стадії повільного сну 15%-20% від загального сну. ",
    not_binded_hint="Прив\'язати Mi Band до акаунту",
    not_binded_hint_info="Також можна натиснути Weight Scale в меню",
    new_record_info="Ви встановили новий рекорд!",
    new_record_format="Кроків: %d | Дата: %d.%s",
    today_goal_reached="Вітаємо! Сьогодні ви досягли своєї мети.",
	today_goal_reached_click_info="Натисніть для перегляду результатів",
    week_continue_reach_goal="Ви досягли мети протягом тижня! Відмінний тиждень!",

    challenge_format="Ви досягли мети за %d дн.!", 
    personal_best_format="Кращий рекорд за %d дн.!",
    continue_with_skips_title="Ви не досягли мети вчора. Нехай це буде день відпочинку ;)",
    continue_with_skips_title_today="Ви не досягли мети сьогодні. Нехай це буде день відпочинку ;)",
    personal_best_with_skips_format="У вас залишилося днів відпочинку: %d ;)",
    continue_used_n_skips_format="Ви досягаєте мети протягом %d дн. поспіль! У вас є днів відпочинку: %d.",
    continue_used_0_skips_format="Ви досягаєте мети протягом %d дн. поспіль! У вас більше немає днів відпочинку.",
    personal_best_on_skip_day_title="%d дн. поспіль! Ви заслужили день відпочинку!",
    personal_best_on_skip_day_info="Після досягнення мети 7 днів поспіль ви отримуєте день відпочинку. Він буде автоматично використаний в день, коли ви не досягнете своєї мети.",
    manual_lazy_title="Ви не досягли мети сьогодні",
    manual_lazy_subtitle="Продовжуйте.",
    manual_lazy_title_used="Сьогодні день відпочинку.",
    manual_lazy_subtitle_used="Ви отримаєте більше днів відпочинку за досягнення нових рекордів.",
    manual_fail_ytd_title = "Тривалість перервана вчора.",
    manual_fail_ytd_subtitle = "Тривалість %d.",

    active_time_format_0="%d хвилин",
    active_time_format_1="%d г.",
    active_time_format_2="%d г. %d хв.",
    activie_run_format_0="Біг %s. Хороша робота!",
    activie_run_format_1="Біг %s. Фантастика!"
    activie_run_format_2="Біг %s. Неймовірна витривалість!",
    activie_run_consumed="Спалено %d ккал. %s",

    get_distance_format="%d м",
	get_distance_format_british="%d дюйма",
    activity_walk_format="%s %d кроків, %s",
    activity_walk_consumed_format="Спалено %d ккал. %s",
    activity_rope_skipping_format="%s стрибків на скакалці: %d",
    activity_situp_format="%s пресс: %d",
    activity_consumed_format="Спалено ккал: %d %s",
    activity_activity_format="%s %s %s",
    activity_activity_format_run="%s %s %s",
    last_night_sleeped_good_format="Сон минулої вночі: %s"
    last_night_sleeped_normal_format="Сон минулої ночі: %s"
    deep_sleep_format="Повільний сон: %s",

    battery_low_info="Низький заряд батареї",
    battery_very_low_info="Зарядіть Mi Band",

    cannot_find_bracelet="Не вдалося знайти Mi Band?",
    cannot_find_bracelet_info="Переконайтеся, що Mi Band знаходиться близько до телефону і заряджений.",
	
	bracelet_disconnect = "Не вдалоя підключитися?"
	
    challenge_to_get="%s дн. з моменту нового рекорду!",
    record_reach_max="Ви побили свій рекорд!",
    new_record_born="Новий рекорд!",

    --=================== Game =====================
    game_register="国庆七天日行万步, 赢取小米手机4",
    game_not_register_info="分享微博赢取微博大奖",
    game_register_info="已成功报名, 倒计时%s天",
    game_playing="国庆七天日行万步, 第%s天挑战中",
    game_playing_done="国庆七天日行万步, 第%s天达成",
    game_playing_lastday="最后一天即将完成日行万步挑战, 加油",
    game_playing_lastday_done="恭喜, 国庆七天日行万步挑战成功",
    game_playing_bonus_info="中将结果将在%s月%s日揭晓",
    click_to_show_result="点击查看活动进展",
    game_fail_title_ytd="很遗憾, 昨天未达成10000步",
    game_fail_title="很遗憾, %s月%s日未达成10000步",
    game_failed_title="国庆七天日行万步",
    game_fail_info="继续关注活动, 分享微博赢取微博大奖",

    game_bonus_hit="恭喜你成为“国庆七天日行万步”获奖者",
    game_bonus_hit_info="点击查看中奖结果",
    game_bonus_miss="国庆七天日行万步, 中奖结果已经揭晓",
    game_bonus_miss_info="快去看看哪些人中奖了吧",
    game_bonus_open="中奖结果将在%s月%s日揭晓, 敬请关注",
    game_bonus_open_tomorrow="中奖结果将在明天揭晓, 敬请关注",
    game_bonus_open_today="中奖结果将在今天揭晓, 敬请关注",

    share_to_content_for_event="“国庆七天日行万步得小米手机4”活动火热报名中，没有手环? 转发此微博即有机会赢取手环F码，点击链接查看活动详情。",
    game_share_to_registered="我报名参加了“日行万步得小米手机4”的活动，你愿意站在一旁默默祝福我还是一起来参加呢？离活动开始只剩%s天了, 快来报名吧",
    game_share_to_finished="今天10000步目标顺利完成",
    game_share_to_not_finished="向着10000步前进",
    game_share_to_failed="没想到呀，我居然挑战失败了",
    game_share_to_success="挑战成功！一共走了%s步",
    game_share_to_hit_bonus="一个不小心中奖了，快来围观给我点赞吧",
    game_share_to_not_hit_bonus="没有抽中，就当是给下次中奖攒人品了",
    less_than_one="小于1",

    ---====== Weather tips ===============
    weather_tips_title_0 = "Сильне забруднення, краще залишіться вдома.",
    weather_tips_title_1 = "Сильне забруднення, краще залишіться вдома.",
    weather_tips_info = "Прес або заняття зі скакалкою - відмінні вправи в приміщенні!",

     ---------------Weight scale -------------------
     welcome_use_weight_scale = "Ласкаво просимо в Weight Scale",
     welcome_use_weight_scale_not_bind = "Прив\'язати Weight Scale",
     welcome_use_mi_health="Ласкаво просимо в Mi Health",
	 
	 select_devices="Немає прив\'язаних пристроїв",
     daily_steps_not_comlete = "Сьогодні ви не досягли мети: %s"
	}