-------------------------
-- English Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140731
-------------------------
localization_ru_rRU_table = {
    calories_table={
		{str="≈ Огурец грунт. (100г)",	calories=14},
		{str="≈ Бульон куриный (100г)",	calories=15},
		{str="≈ Капуста пекинская (100г)",	calories=16},
		{str="≈ Томаты соленые (100г)",	calories=19},
		{str="≈ Квас (100г)",	calories=20},
		{str="≈ Шампиньоны (100г)",	calories=20},
		{str="≈ Редис (100г)",	calories=21},
		{str="≈ Баклажаны (100г)",	calories=24},
		{str="≈ Тыква (100г)",	calories=25},
		{str="≈ Квашеная капуста (100г)",	calories=25},
		{str="≈ Айран (100г)",	calories=26},
		{str="≈ Грибной суп (100г)",	calories=26},
		{str="≈ Брокколи (100г)",	calories=27},
		{str="≈ Овощной суп (100г)",	calories=28},
		{str="≈ Клубника (100г)",	calories=30},
		{str="≈ Щи (100г)",	calories=31},
		{str="≈ Борщ (100г)",	calories=36},
		{str="≈ Суп мисо (100г)",	calories=36},
		{str="≈ Свекольник (100г)",	calories=36},
		{str="≈ Яблоко (100г)",	calories=37},
		{str="≈ Апельсин (100г)",	calories=38},
		{str="≈ Картофельный суп (100г)",	calories=39},
		{str="≈ Арбуз (100г)",	calories=39},
		{str="≈ Суп щавелевый (100г)",	calories=40},
		{str="≈ Простокваша 1% (100г)",	calories=40},
		{str="≈ Рассольник (100г)",	calories=42},
		{str="≈ Кока-Кола (100г)",	calories=42},
		{str="≈ Молоко 1.5% (100г)",	calories=45},
		{str="≈ Red Bull (100г)",	calories=45},
		{str="≈ Уха (100г)",	calories=46},
		{str="≈ Персик (100г)",	calories=46},
		{str="≈ Сыр Хохланд (25г)",	calories=48},
		{str="≈ Вишня (100г)",	calories=52},
		{str="≈ Апельсиновый сок (100г)",	calories=54},
		{str="≈ Кефир 3.2% (100г)",	calories=56},
		{str="≈ Окрошка (100г)",	calories=57},
		{str="≈ Молоко 3.2% (100г)",	calories=58},
		{str="≈ Аджика (100г)",	calories=59},
		{str="≈ Рататуй (100г)",	calories=60},
		{str="≈ Пюре с мол. (100г)",	calories=65},
		{str="≈ Гороховый суп (100г)",	calories=66},
		{str="≈ Манго (100г)",	calories=67},
		{str="≈ Овсяная каша (100г)",	calories=68},
		{str="≈ Суп из чечевицы (100г)",	calories=68},
		{str="≈ Клубничное желе (100г)",	calories=69},
		{str="≈ Солянка сборная (100г)",	calories=69},
		{str="≈ Йогурт 1.5% слад. (100г)",	calories=70},
		{str="≈ Крабовые палочки (100г)",	calories=73},
		{str="≈ Суп харчо (100г)",	calories=75},
		{str="≈ Кальмары (100г)",	calories=75},
		{str="≈ Шампанское (100г)",	calories=76},
		{str="≈ Вино 13% (100г)",	calories=78},
		{str="≈ Вареники с капустой (100г)",	calories=79},
		{str="≈ Гуляш с капустой (100г)",	calories=81},
		{str="≈ Картофель отварной (100г)",	calories=82},
		{str="≈ Абсент 60% (100г)",	calories=83},
		{str="≈ Пюре с мол.и масл. (100г)",	calories=85},
		{str="≈ Яйцо вареное (55г)",	calories=88},
		{str="≈ Банан (100г)",	calories=89},
		{str="≈ Кабачковая икра (100г)",	calories=90},
		{str="≈ Фасоль в томате (100г)",	calories=92},
		{str="≈ Кетчуп (100г)",	calories=93},
		{str="≈ Рис с овощами (100г)",	calories=94},
		{str="≈ Зерновой тост (1шт)",	calories=95},
		{str="≈ Тунец (100г)",	calories=96},
		{str="≈ Судак отварной (100г)",	calories=97},
		{str="≈ Манная каша мол. (100г)",	calories=98},
		{str="≈ Овощное рагу (100г)",	calories=99},
		{str="≈ Карп отварной (100г)",	calories=102},
		{str="≈ Фруктовый салат (100г)",	calories=103},
		{str="≈ Филе индейки (100г)",	calories=104},
		{str="≈ Свинной балык (100г)",	calories=105},
		{str="≈ Плов с курицей (100г)",	calories=106},
		{str="≈ Рис (100г)",	calories=113},
		{str="≈ Цеппелины (100г)",	calories=117},
		{str="≈ Яичница",	calories=119},
		{str="≈ Икра кабачковая (100г)",	calories=122},
		{str="≈ Майонез японский (100г)",	calories=134},
		{str="≈ Зефир (1шт)",	calories=135},
		{str="≈ Творог (100г)",	calories=136},
		{str="≈ Авокадо ролл",	calories=140},
		{str="≈ Капучино (100г)",	calories=140},
		{str="≈ Лобио (100г)",	calories=141},
		{str="≈ Говядина, язык (100г)",	calories=146},
		{str="≈ Говяжий гуляш (100г)",	calories=148},
		{str="≈ Куриное филе вар. (100г)",	calories=153},
		{str="≈ Картошка жар. (100г)",	calories=154},
		{str="≈ Пицца маргарита (100г)",	calories=157},
		{str="≈ Тефтели (100г)",	calories=159},
		{str="≈ Гречневая каша (100г)",	calories=160},
		{str="≈ Сырок Чудо (40г)",	calories=164},
		{str="≈ Хлеб ржаной (100г)",	calories=165},
		{str="≈ Индейка жареная (100г)",	calories=165},
		{str="≈ Салат мимоза (100г)",	calories=183},
		{str="≈ Долма (100г)",	calories=183},
		{str="≈ Копченая курица (100г)",	calories=184},
		{str="≈ Салат Оливье (100г)",	calories=187},
		{str="≈ Зразы картофельные (100г)",	calories=190},
		{str="≈ Биток свиной (100г)",	calories=195},
		{str="≈ Сардельки (100г)",	calories=198},
		{str="≈ Лосось (201г)",	calories=201},
		{str="≈ Сметана 20% (100г)",	calories=204},
		{str="≈ Сливки (100г)",	calories=206},
		{str="≈ Паста болонез (100г)",	calories=208},
		{str="≈ Азу (100г)",	calories=214},
		{str="≈ Хлеб черный (100г)",	calories=214},
		{str="≈ Цукаты (100г)",	calories=216},
		{str="≈ Салат столичный (100г)",	calories=217},
		{str="≈ Сельдь соленая (100г)",	calories=217},
		{str="≈ Жульен грибной (100г)",	calories=219},
		{str="≈ Салат цезарь (100г)",	calories=221},
		{str="≈ Омлет (100г)",	calories=222},
		{str="≈ Светлое пиво (0,5л)",	calories=225},
		{str="≈ Хлеб овсяный (100г)",	calories=226},
		{str="≈ Рагу из баранины (100г)",	calories=226},
		{str="≈ Пломбир (100г)",	calories=227},
		{str="≈ Гамбургер",	calories=229},
		{str="≈ Жаркое из свинины (100г)",	calories=233},
		{str="≈ Батон (100г)",	calories=235},
		{str="≈ Лаваш (100г)",	calories=236},
		{str="≈ Водка 40% (100г)",	calories=237},
		{str="≈ Бастурма (100г)",	calories=240},
		{str="≈ Хамон (100г)",	calories=241},
		{str="≈ Хлеб пшеничный (100г)",	calories=242},
		{str="≈ Сосиски русские (100г)",	calories=243},
		{str="≈ Равиоли (100г)",	calories=245},
		{str="≈ Красная икра (100г)",	calories=249},
		{str="≈ Шаурма (100г)",	calories=250},
		{str="≈ Колбаса вареная (100г)",	calories=257},
		{str="≈ Сосиски куриные (100г)",	calories=259},
		{str="≈ Котлеты (100г)",	calories=260},
		{str="≈ Изюм (100г)",	calories=262},
		{str="≈ Чизбургер",	calories=264},
		{str="≈ Сосиски мол. (100г)",	calories=270},
		{str="≈ Ветчина (100г)",	calories=270},
		{str="≈ Мойва копченая (100г)",	calories=270},
		{str="≈ МакНаггетс (100г)",	calories=272},
		{str="≈ Кровянка (100г)",	calories=274},
		{str="≈ Мясо в шубе (100г)",	calories=274},
		{str="≈ Пельмени (100г)",	calories=275},
		{str="≈ Плов со свининой (100г)",	calories=281},
		{str="≈ Лосось гриль (100г)",	calories=283},
		{str="≈ Сырок Дружба (100г)",	calories=287},
		{str="≈ Черная икра (100г)",	calories=289},
		{str="≈ Майонез (100г)",	calories=299},
		{str="≈ Цветочный мед (100г)",	calories=302},
		{str="≈ Картофель фри (100г)",	calories=303},
		{str="≈ Салат Оливье (100г)",	calories=305},
		{str="≈ Скумбрия соленая (100г)",	calories=305},
		{str="≈ Финики (100г)",	calories=306},
		{str="≈ Оладьи с яблоками (100г)",	calories=306},
		{str="≈ Голубцы (100г)",	calories=311},
		{str="≈ Беляш (100г)",	calories=320},
		{str="≈ Оладьи (100г)",	calories=322},
		{str="≈ Омлет с сыром (100г)",	calories=324},
		{str="≈ Колбаса ливерная (100г)",	calories=326},
		{str="≈ Колбаски охотничьи (100г)",	calories=326},
		{str="≈ Пончики (100г)",	calories=329},
		{str="≈ Ватрушка (100г)",	calories=331},
		{str="≈ Блины с маслом (100г)",	calories=332},
		{str="≈ Люля-кебаб (100г)",	calories=339},
		{str="≈ Сушки (100г)",	calories=341},
		{str="≈ Макароны Макфа (100г)",	calories=344},
		{str="≈ Спагетти (100г)",	calories=344},
		{str="≈ Кекс (100г)",	calories=345},
		{str="≈ Пряник (100г)",	calories=350},
		{str="≈ Бефстроганов (100г)",	calories=355},
		{str="≈ Российский сыр (100г)",	calories=360},
		{str="≈ Кукурузные хлопья (100г)",	calories=363},
		{str="≈ Макароны (100г)",	calories=371},
		{str="≈ Бифштекс (100г)",	calories=384},
		{str="≈ Сухари (100г)",	calories=386},
		{str="≈ Сахар-песок  (100г)",	calories=398},
		{str="≈ Козинаки (100г)",	calories=419},
		{str="≈ Овсяное печенье (100г)",	calories=440},
		{str="≈ Лапша Роллтон  (100г)",	calories=448},
		{str="≈ Торт муравейник (100г)",	calories=452},
		{str="≈ Шницель (100г)",	calories=456},
		{str="≈ Лазанья (100г)",	calories=460},
		{str="≈ Фуа-гра (100г)",	calories=462},
		{str="≈ Торт Медовик  (100г)",	calories=478},
		{str="≈ Попкорн (100г)",	calories=480},
		{str="≈ Твикс",	calories=483},
		{str="≈ Сникерс",	calories=497},
		{str="≈ Бекон (100г)",	calories=500},
		{str="≈ Биг Мак",	calories=510},
		{str="≈ Чипсы Lays Max (100г)",	calories=510},
		{str="≈ Халва (100г)",	calories=522},
		{str="≈ Шоколад KitKat",	calories=524},
		{str="≈ Роял Чизбургер (100г)",	calories=530},
		{str="≈ Тирамису (100г)",	calories=540},
		{str="≈ Чипсы Pringles (100г)",	calories=540},
		{str="≈ Шоколад (100г)",	calories=546},
		{str="≈ Торт Наполеон (100г)",	calories=552},
		{str="≈ Салями (100г)",	calories=568},
		{str="≈ Гусь жареный (100г)",	calories=620},
		{str="≈ Майонез Евр. (100г)",	calories=665},
		{str="≈ Пельмени жареные (100г)",	calories=764},
		{str="≈ Сало (100г)",	calories=797},
		{str="≈ Биг Тейсти",	calories=850},
    },

    ok='ОК',

    hour='ч.',
    minute='мин.',
    month='мес.',
    day='дн.',
    step="ш.",
    km=' км',
    mile='miles',
    minute_format='%d мин.',
    hour_minute_format='%d ч. %d мин.',
    hour_format='%d ч.',

    welcome_use="Добро пожаловать",
    last_week_walked_format='Шагов за прошлую неделю: %d',
    last_week_walked_info_format='Пройдено %d км | Сожжено %d ккал',
    last_month_walked_format='Шагов за прошлый месяц: %d',
    last_month_walked_info_format='Пройдено %d км | Сожжено %d ккал',

    get_over_format=", около %d г жира.",
    click_to_get_help="Информация о Mi Band",
    take_a_walk="Прогуляйтесь с Mi Band",
    take_a_walk_info="Mi Band будет отслеживать вашу активность в течение дня.",
    unlock_hint="Разблокировка с помощью Mi Band",
    unlock_hint_info="Контролируйте доступ к вашему устройству",
	unlock_password_hint="Настройка блокировки экрана для защиты телефона",
    unlock_password_hint_info="Mi Band предоставляет лучшую защиту экрана",
    no_data_hint_0="Двигайтесь, сделайте спорт частью своей жизни.",
    no_data_hint_1="Хотите быть счастливым? Просто бегите.",
    no_data_hint_2="Кардио тренировки сделают тебя бодрым и энергичным на весь день!",
    no_data_hint_3="Взрослый человек проводит в стадии медленного сна 15%-20% от общего сна.",
    not_binded_hint="Привязать Mi Band к аккаунту",
    not_binded_hint_info="Так же можно нажать на весы в меню",
    new_record_info="Вы установили новый рекорд!",
    new_record_format="Шагов: %d | Дата: %d.%s",
    today_goal_reached="Поздравляем! Сегодня вы достигли свою цель.",
	today_goal_reached_click_info="Нажмите для просмотра результатов",
    week_continue_reach_goal="Вы достигали цель на протяжении недели! Отличная неделя!",

    challenge_format="Вы достигаете цель %d дн. подряд!",	
    personal_best_format="Вы достигаете рекорд %d дн.!",
    continue_with_skips_title="Вы не достигли цели вчера. Пусть это будет день отдыха ;)",
    continue_with_skips_title_today="Вы не достигли цели сегодня. Пусть это будет день отдыха ;)",
    personal_best_with_skips_format="У вас осталось дней отдыха: %d ;)",
    continue_used_n_skips_format="Вы достигаете цель на протяжении %d дн. подряд! У вас есть дней отдыха: %d.",
    continue_used_0_skips_format="Вы достигаете цель на протяжении %d дн. подряд! У вас больше нет дней отдыха.",
    personal_best_on_skip_day_title="%d дн. подряд! Вы заслужили день отдыха!",
    personal_best_on_skip_day_info="После достижения цели 7 дней подряд вы получаете день отдыха. Он будет автоматически использован в день, когда вы не достигните свою цель.",
    manual_lazy_title="Вы не достигли цели сегодня",
    manual_lazy_subtitle="Отметьте сегодня как день отдыха и продолжите завтра",
    manual_lazy_title_used="Сегодня день отдыха",
    manual_lazy_subtitle_used="Вы получите больше дней отдыха за достижение новых рекордов",
    manual_fail_ytd_title = "Продолжительность прервана вчера",
    manual_fail_ytd_subtitle = "Продолжительность: %d",

    active_time_format_0="%d мин.",
    active_time_format_1="%d ч.",
    active_time_format_2="%d ч. %d мин.",
    activie_run_format_0="Бег %s. Хорошая работа!",
    activie_run_format_1="Бег %s. Фантастика!",
    activie_run_format_2="Бег %s. Невероятная выносливость!",
    activie_run_consumed="Сожжено %d ккал. %s",
	
    get_distance_format="%d м",
	get_distance_format_british="%d дюйма",
    activity_walk_format="%s Шагов: %d | расстояние: %s",
    activity_walk_consumed_format="Сожжено %d ккал %s",
    activity_rope_skipping_format="%s прыжков на скакалке: %d",
    activity_situp_format="%s пресс: %d",
    activity_consumed_format="Сожжено ккал: %d %s",
    activity_activity_format="%s (%s) расстояние: %s",
    activity_activity_format_run="%s (%s) бег: %s",
    last_night_sleeped_good_format="Сон прошлой ночью: %s",
    last_night_sleeped_normal_format="Сон прошлой ночью: %s",
    deep_sleep_format="Медленный сон: %s",

    battery_low_info="Низкий заряд батареи",
    battery_very_low_info="Зарядите Mi Band",

    cannot_find_bracelet="Не удалось найти Mi Band?",
    cannot_find_bracelet_info="Убедитесь, что Mi Band находится близко к телефону и заряжен.",

    bracelet_disconnect = "Не удалось подключиться?",
	
    challenge_to_get="%s дн. с момента нового рекорда!",
    record_reach_max="Вы побили свой рекорд!",
    new_record_born="Новый рекорд!",

    ---====== Weather tips ===============
    weather_tips_title_0 = "Сильное загрязнение, лучше останьтесь дома.",
    weather_tips_title_1 = "Сильное загрязнение, лучше останьтесь дома.",
    weather_tips_info = "Приседания или занятия со скакалкой - отличные упражнения в помещении!",

    ---------------Weight scale -------------------
    welcome_use_weight_scale = "Добро пожаловать в весы",
	welcome_use_weight_scale_info = "Информация о весах",
    welcome_use_weight_scale_not_bind = "Привязать весы",
    welcome_use_mi_health="Добро пожаловать в Mi Health",
	
	select_devices="Нет привязанных устройств",
    daily_steps_not_comlete = "До достижения цели шагов осталось: %s",

    am_format="%sAM",
    pm_format="%sPM",

    --=============================================
    --===== 不要翻译的内容记载在下面====================
    --=============================================

    --=================== Game ====================
    game_register="国庆七天日行万步, 赢取小米手机4",
    game_not_register_info="分享微博赢取微博大奖",
    game_register_info="已成功报名, 倒计时%s天",
    game_playing="国庆七天日行万步, 第%s天挑战中",
    game_playing_done="国庆七天日行万步, 第%s天达成",
    game_playing_lastday="最后一天即将完成日行万步挑战, 加油",
    game_playing_lastday_done="恭喜, 国庆七天日行万步挑战成功",
    game_playing_bonus_info="中将结果将在%s月%s日揭晓",
    click_to_show_result="点击查看活动进展",
    game_fail_title_ytd="很遗憾, 昨天未达成10000步",
    game_fail_title="很遗憾, %s月%s日未达成10000步",
    game_failed_title="国庆七天日行万步",
    game_fail_info="继续关注活动, 分享微博赢取微博大奖",

    game_bonus_hit="恭喜你成为“国庆七天日行万步”获奖者",
    game_bonus_hit_info="点击查看中奖结果",
    game_bonus_miss="国庆七天日行万步, 中奖结果已经揭晓",
    game_bonus_miss_info="快去看看哪些人中奖了吧",
    game_bonus_open="中奖结果将在%s月%s日揭晓, 敬请关注",
    game_bonus_open_tomorrow="中奖结果将在明天揭晓, 敬请关注",
    game_bonus_open_today="中奖结果将在今天揭晓, 敬请关注",

    share_to_content_for_event="“国庆七天日行万步得小米手机4”活动火热报名中，没有手环? 转发此微博即有机会赢取手环F码，点击链接查看活动详情。",
    game_share_to_registered="我报名参加了“日行万步得小米手机4”的活动，你愿意站在一旁默默祝福我还是一起来参加呢？离活动开始只剩%s天了, 快来报名吧",
    game_share_to_finished="今天10000步目标顺利完成",
    game_share_to_not_finished="向着10000步前进",
    game_share_to_failed="没想到呀，我居然挑战失败了",
    game_share_to_success="挑战成功！一共走了%s步",
    game_share_to_hit_bonus="一个不小心中奖了，快来围观给我点赞吧",
    game_share_to_not_hit_bonus="没有抽中，就当是给下次中奖攒人品了",
    less_than_one="小于1",


}
